name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'output/Conversion-4-29-2025T0 8/Output/SnowConvert/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install schemachange
        run: pip install schemachange

      - name: Create schemachange config
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          mkdir -p ~/.schemachange

          cat <<EOF > ~/.schemachange/connections.toml
          [connections]
            [connections.default]
            account = "${SF_ACCOUNT}"
            user = "${SF_USERNAME}"
            password = "${SF_PASSWORD}"
            role = "${SF_ROLE}"
            warehouse = "${SF_WAREHOUSE}"
            database = "${SF_DATABASE}"
            schema = "SCHEMACHANGE"
          EOF

      - name: Run schemachange
        run: |
          schemachange deploy \
            --config-folder ~/.schemachange \
            --connection-name default \
            -f $GITHUB_WORKSPACE/output/Conversion-4-29-2025T0\ 8/Output/SnowConvert \
            --change-history-table CHANGE_HISTORY \
            --create-change-history-table
