name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'output/Conversion-4-29-2025T0 8/Output/SnowConvert/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange
        env:
          SF_ACCOUNT: 'A9752755683171-ELAIT_PARTNER'
          SF_USERNAME: 'SVA_ELAIT'
          SF_ROLE: 'DATADEVELOPER'
          SF_WAREHOUSE: 'COMPUTE_WH'
          SF_DATABASE: 'DEV'
          SNOWFLAKE_PASSWORD: 'Abcd@123456789'
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          echo "$SF_ACCOUNT"
          echo "$SF_USERNAME"
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/output/Conversion-4-29-2025T0\ 8/Output/SnowConvert \ -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
