name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'output/Conversion-4-29-2025T0 8/Output/SnowConvert/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: |
          pip install schemachange

      - name: Run schemachange with key-pair
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo "$SF_PRIVATE_KEY" | base64 --decode > private_key.p8
          schemachange -f $GITHUB_WORKSPACE/migrations \
            -a $SF_ACCOUNT \
            -u $SF_USERNAME \
            --private-key-path private_key.p8 \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
