name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'output/Conversion-4-29-2025T08/Output/SnowConvert/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install schemachange
        run: pip install schemachange

      - name: Create schemachange connection config
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/connections.toml
          [default]
          account = "A9752755683171-ELAIT_PARTNER"
          user = "SVA_ELAIT"
          password = "Abcd@123456789"
          role = "DATADEVELOPER"
          warehouse = "COMPUTE_WH"
          database = "DEV"
          schema = "SNOWCONVERT"
          EOF

      - name: Run schemachange
        run: |
          schemachange deploy \
            --config-folder ~/.snowflake \
            --connection-name default \
            -f "$GITHUB_WORKSPACE/output/Conversion-4-29-2025T08/Output/SnowConvert" \
            --change-history-table CHANGE_HISTORY \
            --create-change-history-table
